#!/bin/bash

complete -cf sudo
complete -o nospace -A command killall

# Enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
  . /etc/bash_completion
fi

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2)" scp sftp ssh

# Add tab completion for play using active tmux sessions and session files available
_play_complete() {
  cat <(tmux list-sessions 2>/dev/null | awk -F ':' '{ print $1 }') \
      <(ls 2>/dev/null ~/.tmux/sessions/)
}
complete -o "default" -o "nospace" -C _play_complete play

if [ -e "$HOME/lib/todo.txt-cli/todo_completion" ]; then
  source "$HOME/lib/todo.txt-cli/todo_copmletion"
  complete -F _todo t
fi
