#!/bin/bash

# PATH additions
PATH=$PATH:/opt/node/bin
PATH=$PATH:/opt/drush/
PATH=$PATH:/opt/android-sdk-linux_x86/platform-tools

# Git credentials
# Not in the repository, to prevent people from accidentally committing under my name
GIT_AUTHOR_NAME="Oskar Schöldström"
GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
git config --global user.name "$GIT_AUTHOR_NAME"
GIT_AUTHOR_EMAIL="public@oxy.fi"
GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
git config --global user.email "$GIT_AUTHOR_EMAIL"
